import { CategoryEnum, ClassEnum, DirectionClassEnum, DirectionEnum, /* EntryTypeEnum, */ TxnStatusEnum } from '../../enums/transaction';
import { TransactionFeeInterface, TransactionChildInterface } from './';

export interface TransactionInterface {
  txnId: number,
  rowId?: string,
  cardId?: number,
  cardNum?: string,
  agreementId?: number,
  agreementNum?: string,
  // entryType?: EntryTypeEnum,
  class?: ClassEnum,
  category?: CategoryEnum,
  direction?: DirectionEnum,
  directionClass?: DirectionClassEnum,
  transactionDetails?: string,
  transactionTypeId?: number,
  transactionTypeCode?: string,
  transactionTypeName?: string,
  transactionDate?: string,
  transactionAmount?: number,
  transactionCurrency?: string,
  billingAmount?: number,
  billingCurrency?: string,
  feeAmount?: number,
  feeCurrency?: string,
  merchant?: string,
  merchantName?: string,
  merchantCity?: string,
  merchantState?: string,
  merchantCountry?: string,
  mcc?: string,
  terminalId?: string;
  authCode?: string,
  rrn?: string,
  txnStatus?: TxnStatusEnum,
  availableAmount?: number,
  availableCurrency?: string,
  fees?: Array<TransactionFeeInterface>,
  responseCode?: string,
  childs?: Array<TransactionChildInterface>,
  acqInstitutionCode ?: string,
  cardDataInputMode?: string,
  terminalType?: string,
  pinVerification?: string,
  cvv2Verification ?: string,
  cavvValidation?: string,
  stan?: string,
}
