// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vostok.Hotline.Data.EF.DbStorage.References;

namespace Vostok.Hotline.Data.EF.Migrations.HotlineReferences
{
    [DbContext(typeof(HotlineReferencesContext))]
    partial class HotlineReferencesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Vostok.Hotline.Data.EF.Entities.References.CountrySetting", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasColumnName("countryCode")
                        .HasColumnType("varchar(3)")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<bool>("IsCountryRisk")
                        .HasColumnName("isCountryRisk")
                        .HasColumnType("bit");

                    b.HasKey("CountryCode");

                    b.ToTable("CountrySettings");
                });

            modelBuilder.Entity("Vostok.Hotline.Data.EF.Entities.References.RefTransactionCode", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnName("code")
                        .HasColumnType("varchar(2)")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("Description")
                        .HasColumnName("description")
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<string>("Rc")
                        .HasColumnName("rc")
                        .HasColumnType("varchar(64)")
                        .HasMaxLength(64)
                        .IsUnicode(false);

                    b.HasKey("Code");

                    b.ToTable("RefTransactionCode","references");
                });
#pragma warning restore 612, 618
        }
    }
}
