// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vostok.Hotline.Data.EF.DbStorage.Core;

namespace Vostok.Hotline.Data.EF.Migrations
{
    [DbContext(typeof(HotlineCoreContext))]
    [Migration("20210611072747_AddTravelEntities")]
    partial class AddTravelEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Vostok.Hotline.Data.EF.Entities.Core.EnvironmentSetting", b =>
                {
                    b.Property<string>("EnvironmentKey")
                        .HasColumnName("environmentKey")
                        .HasColumnType("varchar(128)")
                        .HasMaxLength(128)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnName("createdOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnvironmentValue")
                        .HasColumnName("environmentValue")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<Guid?>("SessionId")
                        .HasColumnName("sessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnName("updatedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("version")
                        .HasColumnType("rowversion");

                    b.HasKey("EnvironmentKey");

                    b.ToTable("EnvironmentSettings");
                });

            modelBuilder.Entity("Vostok.Hotline.Data.EF.Entities.Core.LoggingRequest", b =>
                {
                    b.Property<int>("LoggingRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("loggingRequestId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnName("createdOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasError")
                        .HasColumnName("hasError")
                        .HasColumnType("bit");

                    b.Property<int?>("LoggingOperationType")
                        .HasColumnName("loggingOperationType")
                        .HasColumnType("int");

                    b.Property<int>("LoggingSystemType")
                        .HasColumnName("loggingSystemType")
                        .HasColumnType("int");

                    b.Property<string>("RequestValue")
                        .HasColumnName("requestValue")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("ResponseValue")
                        .HasColumnName("responseValue")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<Guid?>("SessionId")
                        .HasColumnName("sessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UniqueRequestId")
                        .HasColumnName("uniqueRequestId")
                        .HasColumnType("varchar(32)")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnName("updatedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("version")
                        .HasColumnType("rowversion");

                    b.HasKey("LoggingRequestId");

                    b.HasIndex("SessionId");

                    b.HasIndex("UniqueRequestId");

                    b.ToTable("LoggingRequests");
                });

            modelBuilder.Entity("Vostok.Hotline.Data.EF.Entities.Core.Travel", b =>
                {
                    b.Property<int>("TravelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("travelId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("CashWithdrawalLimit")
                        .HasColumnName("cashWithdrawalLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("ContactPhone")
                        .HasColumnName("contactPhone")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnName("createdOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTravel")
                        .HasColumnName("endTravel")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LimitCardTransfers")
                        .HasColumnName("limitCardTransfers")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("SessionId")
                        .HasColumnName("sessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("SolarId")
                        .HasColumnName("solarId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartTravel")
                        .HasColumnName("startTravel")
                        .HasColumnType("datetime2");

                    b.Property<int>("TravelStatus")
                        .HasColumnName("travelStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnName("updatedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("version")
                        .HasColumnType("rowversion");

                    b.HasKey("TravelId");

                    b.HasIndex("SessionId");

                    b.ToTable("Travels","dbo");
                });

            modelBuilder.Entity("Vostok.Hotline.Data.EF.Entities.Core.TravelCard", b =>
                {
                    b.Property<int>("TravelCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("travelCardId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CardId")
                        .HasColumnName("cardId")
                        .HasColumnType("bigint");

                    b.Property<string>("CardMaskNumber")
                        .HasColumnName("cardMaskNumber")
                        .HasColumnType("varchar(32)")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnName("createdOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SessionId")
                        .HasColumnName("sessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TravelId")
                        .HasColumnName("travelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnName("updatedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("version")
                        .HasColumnType("rowversion");

                    b.HasKey("TravelCardId");

                    b.HasIndex("SessionId");

                    b.HasIndex("TravelId");

                    b.ToTable("TravelCards","dbo");
                });

            modelBuilder.Entity("Vostok.Hotline.Data.EF.Entities.Core.TravelCountry", b =>
                {
                    b.Property<int>("TravelCountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("travelCountryId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnName("countryCode")
                        .HasColumnType("varchar(3)")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnName("createdOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("RiskCountry")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("riskCountry")
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("SessionId")
                        .HasColumnName("sessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TravelId")
                        .HasColumnName("travelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnName("updatedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("version")
                        .HasColumnType("rowversion");

                    b.HasKey("TravelCountryId");

                    b.HasIndex("SessionId");

                    b.HasIndex("TravelId");

                    b.ToTable("TravelCountries","dbo");
                });

            modelBuilder.Entity("Vostok.Hotline.Data.EF.Entities.Core.UserProfile", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("userId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Avatar")
                        .HasColumnName("avatar")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnName("createdOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("email")
                        .HasColumnType("varchar(48)")
                        .HasMaxLength(48)
                        .IsUnicode(false);

                    b.Property<string>("FullName")
                        .HasColumnName("fullName")
                        .HasColumnType("varchar(96)")
                        .HasMaxLength(96)
                        .IsUnicode(false);

                    b.Property<DateTime?>("LastDateLogin")
                        .HasColumnName("lastDateLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnName("login")
                        .HasColumnType("varchar(32)")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<string>("Position")
                        .HasColumnName("position")
                        .HasColumnType("varchar(48)")
                        .HasMaxLength(48)
                        .IsUnicode(false);

                    b.Property<Guid?>("SessionId")
                        .HasColumnName("sessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("SuccessfulDateLogin")
                        .HasColumnName("successfulDateLogin")
                        .HasColumnType("datetime2");

                    b.Property<byte>("UnSuccessfulLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("unSuccessfulLogin")
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnName("updatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserSessionId")
                        .HasColumnName("userSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("version")
                        .HasColumnType("rowversion");

                    b.HasKey("UserId");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("SessionId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Vostok.Hotline.Data.EF.Entities.Core.TravelCard", b =>
                {
                    b.HasOne("Vostok.Hotline.Data.EF.Entities.Core.Travel", "Travel")
                        .WithMany("TravelCards")
                        .HasForeignKey("TravelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Vostok.Hotline.Data.EF.Entities.Core.TravelCountry", b =>
                {
                    b.HasOne("Vostok.Hotline.Data.EF.Entities.Core.Travel", "Travel")
                        .WithMany("TravelCountries")
                        .HasForeignKey("TravelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
